In [1]:
# Zelle 1: Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
import io
import base64
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc, accuracy_score, precision_score, recall_score, f1_score
import pymongo
import os
from tensorflow.keras.utils import Sequence, to_categorical
import gc  # Garbage Collector

2024-11-08 13:42:03.835436: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-08 13:42:03.858041: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-08 13:42:04.180883: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
# Zelle 2: Datenbankverbindung und Datenladung
def load_data():
    mongo_uri = os.getenv('MONGO_URI', 'mongodb://localhost:27017/fingerprintDB')
    client = pymongo.MongoClient(mongo_uri)
    db = client.get_default_database()
    
    # Daten laden
    canvassamples = list(db['canvassamples'].find())
    fingerprints = list(db['fingerprints'].find())
    
    # In DataFrames konvertieren
    canvassamples_df = pd.DataFrame(canvassamples)
    fingerprints_df = pd.DataFrame(fingerprints)
    
    # Merge der DataFrames
    merged_df = pd.merge(canvassamples_df, fingerprints_df, 
                        left_on='fingerprintId', 
                        right_on='_id', 
                        suffixes=('_sample', '_fingerprint'))
    
    return merged_df

# Daten laden
merged_df = load_data()
print(f"Gesamtdatensatz enthält {len(merged_df)} Einträge.")

Gesamtdatensatz enthält 2000000 Einträge.

In [ ]:
# Benutzer-IDs extrahieren
user_ids = merged_df['username'].unique()

# DataFrames für jeden Benutzer erstellen
user_dfs = {user_id: merged_df[merged_df['username'] == user_id] for user_id in user_ids}

# Beispielhafte Anzeige der ersten 5 Zeilen für jeden Benutzer
for user_id, df in user_dfs.items():
    print(f"Erste 5 Zeilen für Benutzer {user_id}:")
    display(df.head())

Erste 5 Zeilen für Benutzer benutzername_1:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
0,66e326e9fab6918841db55df,66e326e8fab6918841db55d1,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-09-12 17:37:45.906,0,66e326e8fab6918841db55d1,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",609903dc45201305b1c661643326d37bacd216f3c4fe13...,benutzername_1,Benutzer 1,ThinkPad E14 Gen 5,Windows 11,100000,2024-09-12 17:37:44.458,0
1,66e326e9fab6918841db55db,66e326e8fab6918841db55d1,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-09-12 17:37:45.847,0,66e326e8fab6918841db55d1,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",609903dc45201305b1c661643326d37bacd216f3c4fe13...,benutzername_1,Benutzer 1,ThinkPad E14 Gen 5,Windows 11,100000,2024-09-12 17:37:44.458,0
2,66e326e9fab6918841db55d6,66e326e8fab6918841db55d1,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-09-12 17:37:45.772,0,66e326e8fab6918841db55d1,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",609903dc45201305b1c661643326d37bacd216f3c4fe13...,benutzername_1,Benutzer 1,ThinkPad E14 Gen 5,Windows 11,100000,2024-09-12 17:37:44.458,0
3,66e326e9fab6918841db55e3,66e326e8fab6918841db55d1,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-09-12 17:37:45.981,0,66e326e8fab6918841db55d1,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",609903dc45201305b1c661643326d37bacd216f3c4fe13...,benutzername_1,Benutzer 1,ThinkPad E14 Gen 5,Windows 11,100000,2024-09-12 17:37:44.458,0
4,66e326eafab6918841db55eb,66e326e8fab6918841db55d1,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-09-12 17:37:46.118,0,66e326e8fab6918841db55d1,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",609903dc45201305b1c661643326d37bacd216f3c4fe13...,benutzername_1,Benutzer 1,ThinkPad E14 Gen 5,Windows 11,100000,2024-09-12 17:37:44.458,0

Erste 5 Zeilen für Benutzer benutzername_3:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
100000,6703f8369717b7a0d179d6e3,6703f8339717b7a0d179d6df,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:03:18.318,0,6703f8339717b7a0d179d6df,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",0bfc7806ac7a11fd13a1a7cb8a309468179bf64f711eb3...,benutzername_3,Benutzer 3,iPhone 11,IOS 17.5.1,100000,2024-10-07 15:03:15.273,0
100001,6703f8369717b7a0d179d6e7,6703f8339717b7a0d179d6df,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:03:18.339,0,6703f8339717b7a0d179d6df,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",0bfc7806ac7a11fd13a1a7cb8a309468179bf64f711eb3...,benutzername_3,Benutzer 3,iPhone 11,IOS 17.5.1,100000,2024-10-07 15:03:15.273,0
100002,6703f8369717b7a0d179d6eb,6703f8339717b7a0d179d6df,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:03:18.359,0,6703f8339717b7a0d179d6df,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",0bfc7806ac7a11fd13a1a7cb8a309468179bf64f711eb3...,benutzername_3,Benutzer 3,iPhone 11,IOS 17.5.1,100000,2024-10-07 15:03:15.273,0
100003,6703f8369717b7a0d179d6ef,6703f8339717b7a0d179d6df,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:03:18.379,0,6703f8339717b7a0d179d6df,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",0bfc7806ac7a11fd13a1a7cb8a309468179bf64f711eb3...,benutzername_3,Benutzer 3,iPhone 11,IOS 17.5.1,100000,2024-10-07 15:03:15.273,0
100004,6703f8369717b7a0d179d6f7,6703f8339717b7a0d179d6df,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:03:18.412,0,6703f8339717b7a0d179d6df,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",0bfc7806ac7a11fd13a1a7cb8a309468179bf64f711eb3...,benutzername_3,Benutzer 3,iPhone 11,IOS 17.5.1,100000,2024-10-07 15:03:15.273,0

Erste 5 Zeilen für Benutzer benutzername_4:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
200000,6704027c9717b7a0d17f22af,6704027b9717b7a0d17f219a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:47:08.952,0,6704027b9717b7a0d17f219a,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",3136a4e8ed34934d00c2532b7f51066763fbbd8e13f3ef...,benutzername_4,Benutzer 4,Motorola 60,Android 11,100000,2024-10-07 15:47:07.157,0
200001,6704027d9717b7a0d17f22b8,6704027b9717b7a0d17f219a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:47:09.010,0,6704027b9717b7a0d17f219a,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",3136a4e8ed34934d00c2532b7f51066763fbbd8e13f3ef...,benutzername_4,Benutzer 4,Motorola 60,Android 11,100000,2024-10-07 15:47:07.157,0
200002,6704027d9717b7a0d17f22c5,6704027b9717b7a0d17f219a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:47:09.039,0,6704027b9717b7a0d17f219a,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",3136a4e8ed34934d00c2532b7f51066763fbbd8e13f3ef...,benutzername_4,Benutzer 4,Motorola 60,Android 11,100000,2024-10-07 15:47:07.157,0
200003,6704027d9717b7a0d17f22cd,6704027b9717b7a0d17f219a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:47:09.060,0,6704027b9717b7a0d17f219a,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",3136a4e8ed34934d00c2532b7f51066763fbbd8e13f3ef...,benutzername_4,Benutzer 4,Motorola 60,Android 11,100000,2024-10-07 15:47:07.157,0
200004,6704027d9717b7a0d17f22d5,6704027b9717b7a0d17f219a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:47:09.086,0,6704027b9717b7a0d17f219a,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",3136a4e8ed34934d00c2532b7f51066763fbbd8e13f3ef...,benutzername_4,Benutzer 4,Motorola 60,Android 11,100000,2024-10-07 15:47:07.157,0

Erste 5 Zeilen für Benutzer benutzername_5:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
300000,670405769717b7a0d181cd21,670405759717b7a0d181cc3f,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:59:50.444,0,670405759717b7a0d181cc3f,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",dca4a9bb1c2f6a6238fd0ad29e2c2d6567b1bbf1e0447f...,benutzername_5,Benutzer 5,iPhone 7,IOS 15.7,100000,2024-10-07 15:59:49.152,0
300001,670405769717b7a0d181cd2c,670405759717b7a0d181cc3f,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:59:50.470,0,670405759717b7a0d181cc3f,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",dca4a9bb1c2f6a6238fd0ad29e2c2d6567b1bbf1e0447f...,benutzername_5,Benutzer 5,iPhone 7,IOS 15.7,100000,2024-10-07 15:59:49.152,0
300002,670405769717b7a0d181cd34,670405759717b7a0d181cc3f,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:59:50.492,0,670405759717b7a0d181cc3f,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",dca4a9bb1c2f6a6238fd0ad29e2c2d6567b1bbf1e0447f...,benutzername_5,Benutzer 5,iPhone 7,IOS 15.7,100000,2024-10-07 15:59:49.152,0
300003,670405769717b7a0d181cd44,670405759717b7a0d181cc3f,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:59:50.533,0,670405759717b7a0d181cc3f,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",dca4a9bb1c2f6a6238fd0ad29e2c2d6567b1bbf1e0447f...,benutzername_5,Benutzer 5,iPhone 7,IOS 15.7,100000,2024-10-07 15:59:49.152,0
300004,670405769717b7a0d181cd4c,670405759717b7a0d181cc3f,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 15:59:50.555,0,670405759717b7a0d181cc3f,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",dca4a9bb1c2f6a6238fd0ad29e2c2d6567b1bbf1e0447f...,benutzername_5,Benutzer 5,iPhone 7,IOS 15.7,100000,2024-10-07 15:59:49.152,0

Erste 5 Zeilen für Benutzer benutzername_6:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
400000,670418789717b7a0d18c7e49,670418779717b7a0d18c7e44,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:20:56.882,0,670418779717b7a0d18c7e44,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",8976859842e60b401714b35ab0e6b68e0002076ca0571e...,benutzername_6,Benutzer 6,S24 Samsung,Android 14,100000,2024-10-07 17:20:55.198,0
400001,670418789717b7a0d18c7e4d,670418779717b7a0d18c7e44,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:20:56.910,0,670418779717b7a0d18c7e44,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",8976859842e60b401714b35ab0e6b68e0002076ca0571e...,benutzername_6,Benutzer 6,S24 Samsung,Android 14,100000,2024-10-07 17:20:55.198,0
400002,670418789717b7a0d18c7e51,670418779717b7a0d18c7e44,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:20:56.934,0,670418779717b7a0d18c7e44,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",8976859842e60b401714b35ab0e6b68e0002076ca0571e...,benutzername_6,Benutzer 6,S24 Samsung,Android 14,100000,2024-10-07 17:20:55.198,0
400003,670418789717b7a0d18c7e55,670418779717b7a0d18c7e44,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:20:56.957,0,670418779717b7a0d18c7e44,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",8976859842e60b401714b35ab0e6b68e0002076ca0571e...,benutzername_6,Benutzer 6,S24 Samsung,Android 14,100000,2024-10-07 17:20:55.198,0
400004,670418789717b7a0d18c7e59,670418779717b7a0d18c7e44,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:20:56.977,0,670418779717b7a0d18c7e44,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",8976859842e60b401714b35ab0e6b68e0002076ca0571e...,benutzername_6,Benutzer 6,S24 Samsung,Android 14,100000,2024-10-07 17:20:55.198,0

Erste 5 Zeilen für Benutzer benutzername_7:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
500000,67041a8f9717b7a0d18d85b4,67041a8d9717b7a0d18d852a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:29:51.007,0,67041a8d9717b7a0d18d852a,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",c7b40c7a9a41fbb753dde543de4332252a4c0c433887df...,benutzername_7,Benutzer 7,iPhone SE,IOS 15.4.1,100000,2024-10-07 17:29:49.467,0
500001,67041a8f9717b7a0d18d85bc,67041a8d9717b7a0d18d852a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:29:51.026,0,67041a8d9717b7a0d18d852a,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",c7b40c7a9a41fbb753dde543de4332252a4c0c433887df...,benutzername_7,Benutzer 7,iPhone SE,IOS 15.4.1,100000,2024-10-07 17:29:49.467,0
500002,67041a8f9717b7a0d18d85c0,67041a8d9717b7a0d18d852a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:29:51.041,0,67041a8d9717b7a0d18d852a,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",c7b40c7a9a41fbb753dde543de4332252a4c0c433887df...,benutzername_7,Benutzer 7,iPhone SE,IOS 15.4.1,100000,2024-10-07 17:29:49.467,0
500003,67041a8f9717b7a0d18d85c4,67041a8d9717b7a0d18d852a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:29:51.057,0,67041a8d9717b7a0d18d852a,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",c7b40c7a9a41fbb753dde543de4332252a4c0c433887df...,benutzername_7,Benutzer 7,iPhone SE,IOS 15.4.1,100000,2024-10-07 17:29:49.467,0
500004,67041a8f9717b7a0d18d85cc,67041a8d9717b7a0d18d852a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:29:51.072,0,67041a8d9717b7a0d18d852a,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",c7b40c7a9a41fbb753dde543de4332252a4c0c433887df...,benutzername_7,Benutzer 7,iPhone SE,IOS 15.4.1,100000,2024-10-07 17:29:49.467,0

Erste 5 Zeilen für Benutzer benutzername_8:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
600000,67041c8b9717b7a0d18f0dc6,67041c899717b7a0d18f0c7f,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:38:19.356,0,67041c899717b7a0d18f0c7f,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",8fe1f7c27e7c122659b6b6689fe84c498eb166c5a7259a...,benutzername_8,Benutzer 8,Tab S6 Lite,Android 13,100000,2024-10-07 17:38:17.666,0
600001,67041c8b9717b7a0d18f0dd6,67041c899717b7a0d18f0c7f,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:38:19.422,0,67041c899717b7a0d18f0c7f,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",8fe1f7c27e7c122659b6b6689fe84c498eb166c5a7259a...,benutzername_8,Benutzer 8,Tab S6 Lite,Android 13,100000,2024-10-07 17:38:17.666,0
600002,67041c8b9717b7a0d18f0de2,67041c899717b7a0d18f0c7f,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:38:19.489,0,67041c899717b7a0d18f0c7f,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",8fe1f7c27e7c122659b6b6689fe84c498eb166c5a7259a...,benutzername_8,Benutzer 8,Tab S6 Lite,Android 13,100000,2024-10-07 17:38:17.666,0
600003,67041c8b9717b7a0d18f0df3,67041c899717b7a0d18f0c7f,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:38:19.556,0,67041c899717b7a0d18f0c7f,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",8fe1f7c27e7c122659b6b6689fe84c498eb166c5a7259a...,benutzername_8,Benutzer 8,Tab S6 Lite,Android 13,100000,2024-10-07 17:38:17.666,0
600004,67041c8b9717b7a0d18f0dfe,67041c899717b7a0d18f0c7f,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:38:19.625,0,67041c899717b7a0d18f0c7f,"{""UserAgent"":""Mozilla/5.0 (Linux; Android 10; ...",8fe1f7c27e7c122659b6b6689fe84c498eb166c5a7259a...,benutzername_8,Benutzer 8,Tab S6 Lite,Android 13,100000,2024-10-07 17:38:17.666,0

Erste 5 Zeilen für Benutzer benutzername_9:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
700000,67041e049717b7a0d1907281,67041e029717b7a0d19070cc,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:44:36.233,0,67041e029717b7a0d19070cc,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",705511461984cfdf5c9f3a279006f476dfda387f8de3e2...,benutzername_9,Benutzer 9,iPhone 5 SE,IOS 14.4.1,100000,2024-10-07 17:44:34.544,0
700001,67041e049717b7a0d190728f,67041e029717b7a0d19070cc,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:44:36.292,0,67041e029717b7a0d19070cc,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",705511461984cfdf5c9f3a279006f476dfda387f8de3e2...,benutzername_9,Benutzer 9,iPhone 5 SE,IOS 14.4.1,100000,2024-10-07 17:44:34.544,0
700002,67041e049717b7a0d190729b,67041e029717b7a0d19070cc,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:44:36.347,0,67041e029717b7a0d19070cc,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",705511461984cfdf5c9f3a279006f476dfda387f8de3e2...,benutzername_9,Benutzer 9,iPhone 5 SE,IOS 14.4.1,100000,2024-10-07 17:44:34.544,0
700003,67041e049717b7a0d19072ad,67041e029717b7a0d19070cc,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:44:36.454,0,67041e029717b7a0d19070cc,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",705511461984cfdf5c9f3a279006f476dfda387f8de3e2...,benutzername_9,Benutzer 9,iPhone 5 SE,IOS 14.4.1,100000,2024-10-07 17:44:34.544,0
700004,67041e049717b7a0d19072be,67041e029717b7a0d19070cc,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 17:44:36.532,0,67041e029717b7a0d19070cc,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",705511461984cfdf5c9f3a279006f476dfda387f8de3e2...,benutzername_9,Benutzer 9,iPhone 5 SE,IOS 14.4.1,100000,2024-10-07 17:44:34.544,0

Erste 5 Zeilen für Benutzer benutzername_10:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
800000,670433cd9717b7a0d1a53ac7,670433cb9717b7a0d1a53a35,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 19:17:33.539,0,670433cb9717b7a0d1a53a35,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",eaf6777c6565e57963d5df2ed27969c6102dc0233befc1...,benutzername_10,Benutzer 10,IPhone 8,IOS 14.4.1,100000,2024-10-07 19:17:31.972,0
800001,670433cd9717b7a0d1a53acf,670433cb9717b7a0d1a53a35,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 19:17:33.555,0,670433cb9717b7a0d1a53a35,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",eaf6777c6565e57963d5df2ed27969c6102dc0233befc1...,benutzername_10,Benutzer 10,IPhone 8,IOS 14.4.1,100000,2024-10-07 19:17:31.972,0
800002,670433cd9717b7a0d1a53ad3,670433cb9717b7a0d1a53a35,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 19:17:33.567,0,670433cb9717b7a0d1a53a35,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",eaf6777c6565e57963d5df2ed27969c6102dc0233befc1...,benutzername_10,Benutzer 10,IPhone 8,IOS 14.4.1,100000,2024-10-07 19:17:31.972,0
800003,670433cd9717b7a0d1a53ac3,670433cb9717b7a0d1a53a35,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 19:17:33.524,0,670433cb9717b7a0d1a53a35,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",eaf6777c6565e57963d5df2ed27969c6102dc0233befc1...,benutzername_10,Benutzer 10,IPhone 8,IOS 14.4.1,100000,2024-10-07 19:17:31.972,0
800004,670433cd9717b7a0d1a53ad7,670433cb9717b7a0d1a53a35,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 19:17:33.589,0,670433cb9717b7a0d1a53a35,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",eaf6777c6565e57963d5df2ed27969c6102dc0233befc1...,benutzername_10,Benutzer 10,IPhone 8,IOS 14.4.1,100000,2024-10-07 19:17:31.972,0

Erste 5 Zeilen für Benutzer benutzername_11:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
900000,6704362d9717b7a0d1a7892e,6704362b9717b7a0d1a7876a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 19:27:41.341,0,6704362b9717b7a0d1a7876a,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",ee02f568b0c73b3326594fea0363b8d7171097ed5bf21f...,benutzername_11,Benutzer 11,Home Pc,Windows 11,100000,2024-10-07 19:27:39.666,0
900001,6704362d9717b7a0d1a7893a,6704362b9717b7a0d1a7876a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 19:27:41.367,0,6704362b9717b7a0d1a7876a,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",ee02f568b0c73b3326594fea0363b8d7171097ed5bf21f...,benutzername_11,Benutzer 11,Home Pc,Windows 11,100000,2024-10-07 19:27:39.666,0
900002,6704362d9717b7a0d1a78936,6704362b9717b7a0d1a7876a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 19:27:41.355,0,6704362b9717b7a0d1a7876a,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",ee02f568b0c73b3326594fea0363b8d7171097ed5bf21f...,benutzername_11,Benutzer 11,Home Pc,Windows 11,100000,2024-10-07 19:27:39.666,0
900003,6704362d9717b7a0d1a78942,6704362b9717b7a0d1a7876a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 19:27:41.382,0,6704362b9717b7a0d1a7876a,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",ee02f568b0c73b3326594fea0363b8d7171097ed5bf21f...,benutzername_11,Benutzer 11,Home Pc,Windows 11,100000,2024-10-07 19:27:39.666,0
900004,6704362d9717b7a0d1a7895e,6704362b9717b7a0d1a7876a,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-07 19:27:41.471,0,6704362b9717b7a0d1a7876a,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",ee02f568b0c73b3326594fea0363b8d7171097ed5bf21f...,benutzername_11,Benutzer 11,Home Pc,Windows 11,100000,2024-10-07 19:27:39.666,0

Erste 5 Zeilen für Benutzer benutzername_13:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
1000000,67077e12ffc8085dd6f4a43a,67077e0effc8085dd6f4a42c,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 07:11:14.431,0,67077e0effc8085dd6f4a42c,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",26d8f89ecb7e31e7457b48195af0e4ed1a93b78d3df20e...,benutzername_13,Benutzer 13,Aspire A515-56,Windows 11,100000,2024-10-10 07:11:10.436,0
1000001,67077e12ffc8085dd6f4a435,67077e0effc8085dd6f4a42c,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 07:11:14.398,0,67077e0effc8085dd6f4a42c,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",26d8f89ecb7e31e7457b48195af0e4ed1a93b78d3df20e...,benutzername_13,Benutzer 13,Aspire A515-56,Windows 11,100000,2024-10-10 07:11:10.436,0
1000002,67077e12ffc8085dd6f4a43e,67077e0effc8085dd6f4a42c,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 07:11:14.450,0,67077e0effc8085dd6f4a42c,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",26d8f89ecb7e31e7457b48195af0e4ed1a93b78d3df20e...,benutzername_13,Benutzer 13,Aspire A515-56,Windows 11,100000,2024-10-10 07:11:10.436,0
1000003,67077e12ffc8085dd6f4a442,67077e0effc8085dd6f4a42c,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 07:11:14.462,0,67077e0effc8085dd6f4a42c,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",26d8f89ecb7e31e7457b48195af0e4ed1a93b78d3df20e...,benutzername_13,Benutzer 13,Aspire A515-56,Windows 11,100000,2024-10-10 07:11:10.436,0
1000004,67077e12ffc8085dd6f4a44a,67077e0effc8085dd6f4a42c,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 07:11:14.513,0,67077e0effc8085dd6f4a42c,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",26d8f89ecb7e31e7457b48195af0e4ed1a93b78d3df20e...,benutzername_13,Benutzer 13,Aspire A515-56,Windows 11,100000,2024-10-10 07:11:10.436,0

Erste 5 Zeilen für Benutzer benutzername_14:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
1100000,67078577ffc8085dd6fac4ed,67078572ffc8085dd6fac4e8,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 07:42:47.986,0,67078572ffc8085dd6fac4e8,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",774dc6f985be8f2aa77159113ee14cbab988b07215d4a0...,benutzername_14,Benutzer 14,Tom’s MacBook Air M2,macOS Sonoma 14.6.1,100000,2024-10-10 07:42:42.592,0
1100001,67078578ffc8085dd6fac4f1,67078572ffc8085dd6fac4e8,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 07:42:48.006,0,67078572ffc8085dd6fac4e8,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",774dc6f985be8f2aa77159113ee14cbab988b07215d4a0...,benutzername_14,Benutzer 14,Tom’s MacBook Air M2,macOS Sonoma 14.6.1,100000,2024-10-10 07:42:42.592,0
1100002,67078578ffc8085dd6fac4f5,67078572ffc8085dd6fac4e8,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 07:42:48.019,0,67078572ffc8085dd6fac4e8,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",774dc6f985be8f2aa77159113ee14cbab988b07215d4a0...,benutzername_14,Benutzer 14,Tom’s MacBook Air M2,macOS Sonoma 14.6.1,100000,2024-10-10 07:42:42.592,0
1100003,67078578ffc8085dd6fac501,67078572ffc8085dd6fac4e8,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 07:42:48.060,0,67078572ffc8085dd6fac4e8,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",774dc6f985be8f2aa77159113ee14cbab988b07215d4a0...,benutzername_14,Benutzer 14,Tom’s MacBook Air M2,macOS Sonoma 14.6.1,100000,2024-10-10 07:42:42.592,0
1100004,67078578ffc8085dd6fac4f9,67078572ffc8085dd6fac4e8,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 07:42:48.035,0,67078572ffc8085dd6fac4e8,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",774dc6f985be8f2aa77159113ee14cbab988b07215d4a0...,benutzername_14,Benutzer 14,Tom’s MacBook Air M2,macOS Sonoma 14.6.1,100000,2024-10-10 07:42:42.592,0

Erste 5 Zeilen für Benutzer benutzername_15:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
1200000,67078e94ffc8085dd600e716,67078e8fffc8085dd600e70c,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:21:40.337,0,67078e8fffc8085dd600e70c,"{""UserAgent"":""Mozilla/5.0 (X11; Linux x86_64) ...",aefa27c899f03716a7cbcec07e7fbc2667ab91f3c7b850...,benutzername_15,Benutzer 15,lenovo-thinkpad-e330,Ubuntu 22.04.5 LTS (Jammy Jellyfish),100000,2024-10-10 08:21:35.355,0
1200001,67078e94ffc8085dd600e71a,67078e8fffc8085dd600e70c,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:21:40.353,0,67078e8fffc8085dd600e70c,"{""UserAgent"":""Mozilla/5.0 (X11; Linux x86_64) ...",aefa27c899f03716a7cbcec07e7fbc2667ab91f3c7b850...,benutzername_15,Benutzer 15,lenovo-thinkpad-e330,Ubuntu 22.04.5 LTS (Jammy Jellyfish),100000,2024-10-10 08:21:35.355,0
1200002,67078e94ffc8085dd600e722,67078e8fffc8085dd600e70c,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:21:40.385,0,67078e8fffc8085dd600e70c,"{""UserAgent"":""Mozilla/5.0 (X11; Linux x86_64) ...",aefa27c899f03716a7cbcec07e7fbc2667ab91f3c7b850...,benutzername_15,Benutzer 15,lenovo-thinkpad-e330,Ubuntu 22.04.5 LTS (Jammy Jellyfish),100000,2024-10-10 08:21:35.355,0
1200003,67078e94ffc8085dd600e726,67078e8fffc8085dd600e70c,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:21:40.401,0,67078e8fffc8085dd600e70c,"{""UserAgent"":""Mozilla/5.0 (X11; Linux x86_64) ...",aefa27c899f03716a7cbcec07e7fbc2667ab91f3c7b850...,benutzername_15,Benutzer 15,lenovo-thinkpad-e330,Ubuntu 22.04.5 LTS (Jammy Jellyfish),100000,2024-10-10 08:21:35.355,0
1200004,67078e94ffc8085dd600e71e,67078e8fffc8085dd600e70c,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:21:40.370,0,67078e8fffc8085dd600e70c,"{""UserAgent"":""Mozilla/5.0 (X11; Linux x86_64) ...",aefa27c899f03716a7cbcec07e7fbc2667ab91f3c7b850...,benutzername_15,Benutzer 15,lenovo-thinkpad-e330,Ubuntu 22.04.5 LTS (Jammy Jellyfish),100000,2024-10-10 08:21:35.355,0

Erste 5 Zeilen für Benutzer benutzername_16:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
1300000,67079161ffc8085dd605256d,6707915effc8085dd605222b,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:33:37.164,0,6707915effc8085dd605222b,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",a4341418e1e0a7d283024fb01fd6bbb910d0aee00cb9b0...,benutzername_16,Benutzer 16,iPhone 12 mini,iOS 18.0.1,100000,2024-10-10 08:33:34.904,0
1300001,67079161ffc8085dd6052579,6707915effc8085dd605222b,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:33:37.179,0,6707915effc8085dd605222b,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",a4341418e1e0a7d283024fb01fd6bbb910d0aee00cb9b0...,benutzername_16,Benutzer 16,iPhone 12 mini,iOS 18.0.1,100000,2024-10-10 08:33:34.904,0
1300002,67079161ffc8085dd6052585,6707915effc8085dd605222b,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:33:37.196,0,6707915effc8085dd605222b,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",a4341418e1e0a7d283024fb01fd6bbb910d0aee00cb9b0...,benutzername_16,Benutzer 16,iPhone 12 mini,iOS 18.0.1,100000,2024-10-10 08:33:34.904,0
1300003,67079161ffc8085dd605258d,6707915effc8085dd605222b,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:33:37.209,0,6707915effc8085dd605222b,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",a4341418e1e0a7d283024fb01fd6bbb910d0aee00cb9b0...,benutzername_16,Benutzer 16,iPhone 12 mini,iOS 18.0.1,100000,2024-10-10 08:33:34.904,0
1300004,67079161ffc8085dd6052599,6707915effc8085dd605222b,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:33:37.222,0,6707915effc8085dd605222b,"{""UserAgent"":""Mozilla/5.0 (iPhone; CPU iPhone ...",a4341418e1e0a7d283024fb01fd6bbb910d0aee00cb9b0...,benutzername_16,Benutzer 16,iPhone 12 mini,iOS 18.0.1,100000,2024-10-10 08:33:34.904,0

Erste 5 Zeilen für Benutzer benutzername_17:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
1400000,6707944cffc8085dd60a53fb,67079447ffc8085dd60a4e43,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:46:04.501,0,67079447ffc8085dd60a4e43,"{""UserAgent"":""Mozilla/5.0 (X11; Ubuntu; Linux ...",a74e66483bbfc6d6d507acb1d94ae20eb21d194de6bc9f...,benutzername_17,Benutzer 17,matze-HP-ZBook-Power-15-6-inch-G8-Mobile-Works...,Ubuntu 24.04.1 LTS,100000,2024-10-10 08:45:59.733,0
1400001,6707944cffc8085dd60a5403,67079447ffc8085dd60a4e43,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:46:04.510,0,67079447ffc8085dd60a4e43,"{""UserAgent"":""Mozilla/5.0 (X11; Ubuntu; Linux ...",a74e66483bbfc6d6d507acb1d94ae20eb21d194de6bc9f...,benutzername_17,Benutzer 17,matze-HP-ZBook-Power-15-6-inch-G8-Mobile-Works...,Ubuntu 24.04.1 LTS,100000,2024-10-10 08:45:59.733,0
1400002,6707944cffc8085dd60a540c,67079447ffc8085dd60a4e43,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:46:04.525,0,67079447ffc8085dd60a4e43,"{""UserAgent"":""Mozilla/5.0 (X11; Ubuntu; Linux ...",a74e66483bbfc6d6d507acb1d94ae20eb21d194de6bc9f...,benutzername_17,Benutzer 17,matze-HP-ZBook-Power-15-6-inch-G8-Mobile-Works...,Ubuntu 24.04.1 LTS,100000,2024-10-10 08:45:59.733,0
1400003,6707944cffc8085dd60a5407,67079447ffc8085dd60a4e43,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:46:04.518,0,67079447ffc8085dd60a4e43,"{""UserAgent"":""Mozilla/5.0 (X11; Ubuntu; Linux ...",a74e66483bbfc6d6d507acb1d94ae20eb21d194de6bc9f...,benutzername_17,Benutzer 17,matze-HP-ZBook-Power-15-6-inch-G8-Mobile-Works...,Ubuntu 24.04.1 LTS,100000,2024-10-10 08:45:59.733,0
1400004,6707944cffc8085dd60a5414,67079447ffc8085dd60a4e43,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 08:46:04.541,0,67079447ffc8085dd60a4e43,"{""UserAgent"":""Mozilla/5.0 (X11; Ubuntu; Linux ...",a74e66483bbfc6d6d507acb1d94ae20eb21d194de6bc9f...,benutzername_17,Benutzer 17,matze-HP-ZBook-Power-15-6-inch-G8-Mobile-Works...,Ubuntu 24.04.1 LTS,100000,2024-10-10 08:45:59.733,0

Erste 5 Zeilen für Benutzer benutzername_18:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
1500000,6707b90affc8085dd613465d,6707b908ffc8085dd6134657,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:22:50.819,0,6707b908ffc8085dd6134657,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",edb56be9683b627526ff0c567608b612cd0183115a8839...,benutzername_18,Benutzer 18,Mac Book Pro,Ventura 13.6,100000,2024-10-10 11:22:48.634,0
1500001,6707b90affc8085dd6134661,6707b908ffc8085dd6134657,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:22:50.831,0,6707b908ffc8085dd6134657,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",edb56be9683b627526ff0c567608b612cd0183115a8839...,benutzername_18,Benutzer 18,Mac Book Pro,Ventura 13.6,100000,2024-10-10 11:22:48.634,0
1500002,6707b90affc8085dd6134669,6707b908ffc8085dd6134657,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:22:50.850,0,6707b908ffc8085dd6134657,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",edb56be9683b627526ff0c567608b612cd0183115a8839...,benutzername_18,Benutzer 18,Mac Book Pro,Ventura 13.6,100000,2024-10-10 11:22:48.634,0
1500003,6707b90affc8085dd613466d,6707b908ffc8085dd6134657,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:22:50.863,0,6707b908ffc8085dd6134657,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",edb56be9683b627526ff0c567608b612cd0183115a8839...,benutzername_18,Benutzer 18,Mac Book Pro,Ventura 13.6,100000,2024-10-10 11:22:48.634,0
1500004,6707b90affc8085dd6134671,6707b908ffc8085dd6134657,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:22:50.876,0,6707b908ffc8085dd6134657,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",edb56be9683b627526ff0c567608b612cd0183115a8839...,benutzername_18,Benutzer 18,Mac Book Pro,Ventura 13.6,100000,2024-10-10 11:22:48.634,0

Erste 5 Zeilen für Benutzer benutzername_19:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
1600000,6707baadffc8085dd6162250,6707baabffc8085dd6161f43,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:29:49.650,0,6707baabffc8085dd6161f43,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",7c893f1ca03be6286b0f7e3cfe8b9470bb1b041ca37e8d...,benutzername_19,Benutzer 19,LENOVO 21N10007GE,Microsoft Windows 11 Pro Arm,100000,2024-10-10 11:29:47.971,0
1600001,6707baadffc8085dd6162258,6707baabffc8085dd6161f43,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:29:49.660,0,6707baabffc8085dd6161f43,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",7c893f1ca03be6286b0f7e3cfe8b9470bb1b041ca37e8d...,benutzername_19,Benutzer 19,LENOVO 21N10007GE,Microsoft Windows 11 Pro Arm,100000,2024-10-10 11:29:47.971,0
1600002,6707baadffc8085dd6162261,6707baabffc8085dd6161f43,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:29:49.670,0,6707baabffc8085dd6161f43,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",7c893f1ca03be6286b0f7e3cfe8b9470bb1b041ca37e8d...,benutzername_19,Benutzer 19,LENOVO 21N10007GE,Microsoft Windows 11 Pro Arm,100000,2024-10-10 11:29:47.971,0
1600003,6707baadffc8085dd6162269,6707baabffc8085dd6161f43,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:29:49.679,0,6707baabffc8085dd6161f43,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",7c893f1ca03be6286b0f7e3cfe8b9470bb1b041ca37e8d...,benutzername_19,Benutzer 19,LENOVO 21N10007GE,Microsoft Windows 11 Pro Arm,100000,2024-10-10 11:29:47.971,0
1600004,6707baadffc8085dd6162271,6707baabffc8085dd6161f43,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:29:49.688,0,6707baabffc8085dd6161f43,"{""UserAgent"":""Mozilla/5.0 (Windows NT 10.0; Wi...",7c893f1ca03be6286b0f7e3cfe8b9470bb1b041ca37e8d...,benutzername_19,Benutzer 19,LENOVO 21N10007GE,Microsoft Windows 11 Pro Arm,100000,2024-10-10 11:29:47.971,0

Erste 5 Zeilen für Benutzer benutzername_20:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
1700000,6707bdebffc8085dd61d7c85,6707bdeaffc8085dd61d7b38,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:43:39.742,0,6707bdeaffc8085dd61d7b38,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",27219c9b5b26960ed3ab916c4fa57a1d5980a7c011581f...,benutzername_20,Benutzer 20,Mac Mini 2016,Sonoma 14.3.1,100000,2024-10-10 11:43:38.104,0
1700001,6707bdebffc8085dd61d7c8d,6707bdeaffc8085dd61d7b38,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:43:39.756,0,6707bdeaffc8085dd61d7b38,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",27219c9b5b26960ed3ab916c4fa57a1d5980a7c011581f...,benutzername_20,Benutzer 20,Mac Mini 2016,Sonoma 14.3.1,100000,2024-10-10 11:43:38.104,0
1700002,6707bdebffc8085dd61d7c99,6707bdeaffc8085dd61d7b38,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:43:39.773,0,6707bdeaffc8085dd61d7b38,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",27219c9b5b26960ed3ab916c4fa57a1d5980a7c011581f...,benutzername_20,Benutzer 20,Mac Mini 2016,Sonoma 14.3.1,100000,2024-10-10 11:43:38.104,0
1700003,6707bdebffc8085dd61d7ca1,6707bdeaffc8085dd61d7b38,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:43:39.787,0,6707bdeaffc8085dd61d7b38,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",27219c9b5b26960ed3ab916c4fa57a1d5980a7c011581f...,benutzername_20,Benutzer 20,Mac Mini 2016,Sonoma 14.3.1,100000,2024-10-10 11:43:38.104,0
1700004,6707bdebffc8085dd61d7ca9,6707bdeaffc8085dd61d7b38,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 11:43:39.803,0,6707bdeaffc8085dd61d7b38,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",27219c9b5b26960ed3ab916c4fa57a1d5980a7c011581f...,benutzername_20,Benutzer 20,Mac Mini 2016,Sonoma 14.3.1,100000,2024-10-10 11:43:38.104,0

Erste 5 Zeilen für Benutzer benutzername_21:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
1800000,6707c487ffc8085dd625a040,6707c486ffc8085dd625a03b,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 12:11:51.494,0,6707c486ffc8085dd625a03b,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",ceb06c001f5b9b3b7a6ac3c7e77def777ae8b9c977a4f6...,benutzername_21,Benutzer 21,MacMini M1 2020,Ventura 13.2,100000,2024-10-10 12:11:50.062,0
1800001,6707c487ffc8085dd625a044,6707c486ffc8085dd625a03b,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 12:11:51.506,0,6707c486ffc8085dd625a03b,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",ceb06c001f5b9b3b7a6ac3c7e77def777ae8b9c977a4f6...,benutzername_21,Benutzer 21,MacMini M1 2020,Ventura 13.2,100000,2024-10-10 12:11:50.062,0
1800002,6707c487ffc8085dd625a048,6707c486ffc8085dd625a03b,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 12:11:51.517,0,6707c486ffc8085dd625a03b,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",ceb06c001f5b9b3b7a6ac3c7e77def777ae8b9c977a4f6...,benutzername_21,Benutzer 21,MacMini M1 2020,Ventura 13.2,100000,2024-10-10 12:11:50.062,0
1800003,6707c487ffc8085dd625a04c,6707c486ffc8085dd625a03b,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 12:11:51.528,0,6707c486ffc8085dd625a03b,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",ceb06c001f5b9b3b7a6ac3c7e77def777ae8b9c977a4f6...,benutzername_21,Benutzer 21,MacMini M1 2020,Ventura 13.2,100000,2024-10-10 12:11:50.062,0
1800004,6707c487ffc8085dd625a050,6707c486ffc8085dd625a03b,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 12:11:51.539,0,6707c486ffc8085dd625a03b,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",ceb06c001f5b9b3b7a6ac3c7e77def777ae8b9c977a4f6...,benutzername_21,Benutzer 21,MacMini M1 2020,Ventura 13.2,100000,2024-10-10 12:11:50.062,0

Erste 5 Zeilen für Benutzer benutzername_22:

,_id_sample,fingerprintId,sampleData,createdAt_sample,__v_sample,_id_fingerprint,fingerprint,fingerprintHash,username,name,deviceName,operatingSystem,canvasSampleCount,createdAt_fingerprint,__v_fingerprint
1900000,6707cabdffc8085dd62a72c5,6707cabaffc8085dd62a6eb2,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 12:38:21.957,0,6707cabaffc8085dd62a6eb2,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",7c57994e6cde8672f73c095d7d838960776641b9ac240b...,benutzername_22,Benutzer 22,M2 mac mini,macOS Sequoia 15.0,100000,2024-10-10 12:38:18.801,0
1900001,6707cabdffc8085dd62a72d1,6707cabaffc8085dd62a6eb2,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 12:38:21.970,0,6707cabaffc8085dd62a6eb2,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",7c57994e6cde8672f73c095d7d838960776641b9ac240b...,benutzername_22,Benutzer 22,M2 mac mini,macOS Sequoia 15.0,100000,2024-10-10 12:38:18.801,0
1900002,6707cabdffc8085dd62a72ca,6707cabaffc8085dd62a6eb2,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 12:38:21.964,0,6707cabaffc8085dd62a6eb2,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",7c57994e6cde8672f73c095d7d838960776641b9ac240b...,benutzername_22,Benutzer 22,M2 mac mini,macOS Sequoia 15.0,100000,2024-10-10 12:38:18.801,0
1900003,6707cabdffc8085dd62a72dd,6707cabaffc8085dd62a6eb2,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 12:38:21.981,0,6707cabaffc8085dd62a6eb2,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",7c57994e6cde8672f73c095d7d838960776641b9ac240b...,benutzername_22,Benutzer 22,M2 mac mini,macOS Sequoia 15.0,100000,2024-10-10 12:38:18.801,0
1900004,6707cabdffc8085dd62a72e1,6707cabaffc8085dd62a6eb2,iVBORw0KGgoAAAANSUhEUgAAARgAAAAjCAYAAABPRBVWAA...,2024-10-10 12:38:21.985,0,6707cabaffc8085dd62a6eb2,"{""UserAgent"":""Mozilla/5.0 (Macintosh; Intel Ma...",7c57994e6cde8672f73c095d7d838960776641b9ac240b...,benutzername_22,Benutzer 22,M2 mac mini,macOS Sequoia 15.0,100000,2024-10-10 12:38:18.801,0

:

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
import io
import base64
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc, accuracy_score, precision_score, recall_score, f1_score
from tensorflow.keras.applications import ResNet50, MobileNetV2, EfficientNetB0
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import to_categorical
import gc  # Garbage Collector

# Funktion zur Verarbeitung der Bilder in Graustufen
def process_image_grayscale(base64_str, target_size=(224, 224)):
    try:
        image_data = base64.b64decode(base64_str)
        image = Image.open(io.BytesIO(image_data))
        image = image.convert('L')  # Konvertieren in Graustufen
        image = image.resize(target_size)
        image_array = np.array(image) / 255.0  # Normalisierung auf Werte zwischen 0 und 1
        image_array = np.stack((image_array,)*3, axis=-1)  # Konvertieren in 3-Kanal-Bild
        return image_array
    except Exception as e:
        print(f"Fehler bei der Bildverarbeitung: {e}")
        return None

def extract_images_from_df(df):
    images = []
    labels = []
    for _, row in df.iterrows():
        image = process_image_grayscale(row['sampleData'])
        if image is not None:
            images.append(image)
            labels.append(1 if row['username'] == example_user_id else 0)
    return np.array(images), np.array(labels)

# Benutzer-IDs extrahieren
user_ids = merged_df['username'].unique()

# DataFrames für jeden Benutzer erstellen
user_dfs = {user_id: merged_df[merged_df['username'] == user_id] for user_id in user_ids}

# Beispiel für Benutzer 1
example_user_id = 'benutzername_1'
user_df = user_dfs[example_user_id]

# Negative Beispiele hinzufügen und begrenzen
negative_df = pd.concat([user_dfs[user_id] for user_id in user_ids if user_id != example_user_id])
negative_df = negative_df.sample(n=100000, random_state=42)  # Zufällige Stichprobe von 100.000 negativen Beispielen

# Aufteilung in Train/Val/Test-Sets (70% Train, 20% Val, 10% Test)
train_df, test_df = train_test_split(pd.concat([user_df, negative_df]), test_size=0.1, random_state=42)
train_df, val_df = train_test_split(train_df, test_size=0.2222, random_state=42)  # 0.2222 * 0.9 ≈ 0.2

# Bilddaten verarbeiten
X_train, y_train = extract_images_from_df(train_df)
X_val, y_val = extract_images_from_df(val_df)
X_test, y_test = extract_images_from_df(test_df)

# One-Hot-Encoding der Labels
y_train = to_categorical(y_train, num_classes=2)
y_val = to_categorical(y_val, num_classes=2)
y_test = to_categorical(y_test, num_classes=2)

# Verwendung eines vortrainierten ResNet-Modells
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(2, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=predictions)

for layer in base_model.layers:
    layer.trainable = False

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Modell trainieren
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_val, y_val))

# Zufällige Samples von verschiedenen Benutzern auswählen
random_samples = []
random_labels = []
sample_users = []

# 2 Samples von Benutzer 1
user_df = user_dfs[example_user_id]
samples = user_df.sample(n=2, random_state=42)
random_samples.extend(samples['sampleData'].tolist())
sample_users.extend([example_user_id] * 2)
random_labels.extend([1] * 2)  # Label 1 für Benutzer 1

# 8 Samples von anderen Benutzern
other_user_ids = [user_id for user_id in user_ids if user_id != example_user_id]
for user_id in np.random.choice(other_user_ids, 8, replace=False):
    user_df = user_dfs[user_id]
    sample = user_df.sample(n=1, random_state=42)
    random_samples.extend(sample['sampleData'].tolist())
    sample_users.extend([user_id])
    random_labels.extend([0])  # Label 0 für andere Benutzer

# Bilddaten verarbeiten und Features extrahieren
X_random = np.array([process_image_grayscale(sample) for sample in random_samples])

# Vorhersagen mit dem Modell durchführen
y_pred = model.predict(X_random)
y_pred_classes = np.argmax(y_pred, axis=1)
y_pred_prob = y_pred[:, 1]  # Wahrscheinlichkeiten für Klasse 1 (Benutzer 1)

# Wahrscheinlichkeiten und Labels in einem DataFrame speichern
results_df = pd.DataFrame({
    'User': sample_users,
    'True Label': random_labels,
    'Predicted Label': y_pred_classes
})

# Ob die Vorhersage korrekt ist
results_df['Correct'] = results_df['True Label'] == results_df['Predicted Label']

# Klassifikationstyp hinzufügen
def get_classification(row):
    if row['True Label'] == 1 and row['Predicted Label'] == 1:
        return 'True Positive'
    elif row['True Label'] == 0 and row['Predicted Label'] == 1:
        return 'False Positive'
    elif row['True Label'] == 0 and row['Predicted Label'] == 0:
        return 'True Negative'
    else:
        return 'False Negative'

results_df['Classification'] = results_df.apply(get_classification, axis=1)

# Tabelle anzeigen
display(results_df)

# Farben für True Positives, False Positives, True Negatives und False Negatives
def get_color(row):
    if row['True Label'] == 1 and row['Predicted Label'] == 1:
        return 'green'  # True Positive
    elif row['True Label'] == 0 and row['Predicted Label'] == 1:
        return 'red'    # False Positive
    elif row['True Label'] == 0 and row['Predicted Label'] == 0:
        return 'blue'   # True Negative
    else:
        return 'orange' # False Negative

results_df['Color'] = results_df.apply(get_color, axis=1)

# Graphen erstellen
plt.figure(figsize=(12, 8))
plt.scatter(range(len(results_df)), results_df['Predicted Label'], c=results_df['Color'], alpha=0.5)
plt.title('Klassifikationen für Benutzer 1')
plt.xlabel('Sample Index')
plt.ylabel('Vorhergesagte Klasse')
plt.yticks([0, 1], ['Nicht Benutzer 1', 'Benutzer 1'])
plt.show()

:

: